management 0.0.0.0 2080  # Don't change this line. OpenVPN UI uses this feature to manage the server 

dev {{ .Device }}
port {{ .Port }}
proto {{ .Proto }}

topology {{ .OVConfigTopology }}
keepalive {{ .Keepalive }}
max-clients {{ .MaxClients }}

persist-key
persist-tun
explicit-exit-notify 1

user {{ .OVConfigUser }}
group {{ .OVConfigGroup }}

client-config-dir {{ .OVConfigClientConfigDir }}
ifconfig-pool-persist {{ .IfconfigPoolPersist }}

ca {{ .Ca }}
cert {{ .Cert }}
key {{ .Key }}
crl-verify {{ .Crl }}
dh {{ .Dh }}

{{ .TLSControlChannel }}
{{ .TLSMinVersion }}
{{ .TLSRemoteCert }}

cipher {{ .Cipher }}
# ncp-ciphers {{ .OVConfigNcpCiphers }}   # Deprecated since ver. 0.9.3. We have to use data-ciphers below instead
data-ciphers {{ .OVConfigNcpCiphers }}

auth {{ .Auth }}

{{ .Server }}           # Trusted VPN subnet
{{ .Route }}            # Route to Guest VPN subnet
{{ .PushRoute }}     # Route to Home VPN subnet
{{ .DNSServer1 }}             # DNS1 server for VPN clients
{{ .DNSServer2 }}             # DNS2 server for VPN clients
{{ .RedirectGW }}    # Redirect gateway for VPN clients

log {{ .OVConfigLogfile }}
verb {{ .OVConfigLogVerbose }}
status {{ .OVConfigStatusLog }}
status-version {{ .OVConfigStatusLogVersion }}

{{ .ScriptSecurity }}
{{ .UserPassVerify }}

{{ .CustomOptOne }}
{{ .CustomOptTwo }}
{{ .CustomOptThree }}

# ======================= NiceVPN hooks & telemetry ============================
script-security 2

# Идентификатор инстанса для логов и метрик
setenv OPENVPN_INSTANCE server-gost

# Логирование TLS-фазы (сертификаты, untrusted_ip, цепочка)
tls-verify "/usr/libexec/nicevpn/tls-verify.sh"

# (опционально) Логин/пароль через скрипт + лог auth_attempt
#auth-user-pass-verify "/usr/libexec/nicevpn/auth-user-pass-verify.sh via-file"
#username-as-common-name

# Текущие скрипты подключения/отключения.
# Внутри них нужно дергать event-logger.py (см. ниже).
client-connect /usr/libexec/nicevpn/client-connect.sh
client-disconnect /usr/libexec/nicevpn/client-disconnect.sh

# Привязка VPN-IP к CN (и группам) + лог ip_bind/ip_unbind
learn-address "/usr/libexec/nicevpn/learn-address.sh"

# Пробрасываем peer info от клиента (IV_*, UV_*, IV_GUI_VER, IV_PLAT, IV_CIPHERS, ...)
push-peer-info

# Auto generated by OpenVPN-UI v.0.9.5.6
